language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*
    - php: 7
      env: SYMFONY_VERSION=3.1.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 7
      env: SYMFONY_VERSION=3.0.*

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - phpunit

services:
  - mysql

before_script:
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -e 'CREATE DATABASE dftests'

after_script:
    - mysql -e 'DROP DATABASE dftests;'

notifications:
  email: contact@discutea.com
