<?php

namespace Discutea\DForumBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * METHODS LIST:
 * findLast($limit) Return lastPosts list
 * 
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * infos: Update LastPost on postPersist
     *
     * @param int $limit
     * @return array $lastPosts (List of last posts)
     */
    public function findLast($limit) 
    {
        $lastPosts = $this->findBy(
            array(),
            array('date' => 'desc'),
            $limit,
            0
        );
        
        return $lastPosts;
    }

    /**
     * infos: Find lastEdited 
     *
     * @param class Discutea\DForumBundle\Entity\Forum $forum
     * @return array $forumsList
     */
    public function findLastEdited()
    {
        
        $qb = $this->createQueryBuilder('p');
   
        $qb->where('p.updated is not null')
           ->addOrderBy("p.updated", 'ASC');
    
        return $qb->getQuery()->getResult();
    }

}
