<?php
namespace Discutea\DForumBundle\Repository;

use Discutea\DForumBundle\Entity\Forum;
/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 * METHODS LIST:
 * findLast($limit) Return lastTopics list
 * findAllByForumOrderedByDate($forum, $order = 'DESC') Return forums list ordored by Datetime desc
 * 
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * infos: Find lastTopics list
     *
     * @param int $limit
     * @return array $lastTopics
     */
    public function findLast($limit) 
    {
        $lastTopics = $this->findBy(
            array(),
            array('date' => 'desc'),
            $limit,
            0
        );
        
        return $lastTopics;
    }

    /**
     * infos: Find lastTopics list
     *
     * @param class Discutea\DForumBundle\Entity\Forum $forum
     * @return array $forumsList
     */
    public function findAllByForumOrderedByDate(Forum $forum, $order = 'DESC')
    {
        
        $qb = $this->createQueryBuilder('t');
   
        $qb->where('t.forum = :forum')
           ->setParameter('forum', $forum)
           ->join('t.posts', 'p')
           ->orderBy("t.pinned", 'DESC')
           ->addOrderBy("t.lastPost", $order);
    
        return $qb->getQuery()->getResult();
    }
}
